chore(deps): refactor docker mysql
line/abc-user-feedback pull request #451
Opened 2024-06-25 23:55 UTC by IMHOJEONG

Hello, thank you for creating a great project. 

Command differences and opensearch password settings have been added depending on the mysql service version. 

I changed the platform settings based on my operating system.

My operating system environment is as follows.

OS : Apple M1 Pro, Ventura 13.4 
Docker Version: Docker Desktop v26.1.4
Editor: Visual Studio Code

PS. When executing the command below, I wish there was a message telling you to delete the docker/volume folder and then run it.

> 2. Spin up all required infrastructure (Mysql, OpenSearch, etc.) using Docker Compose:
> docker-compose -f docker/docker-compose.infra.yml up -d

https://dev.mysql.com/doc/refman/8.4/en/data-directory-initialization.html#data-directory-initialization-overview

> If the data directory exists but is not empty (that is, it contains files or subdirectories), the server exits after producing an error message:

> [ERROR] --initialize specified but the data directory exists. Aborting.

The reason is that because it checks whether the data directory exists as above, an error such as a link occurs. 

thank you

2024-06-26 05:11 UTC, h4l-yup requested changes

2024-06-26 05:11 UTC, h4l-yup commented on docker/docker-compose.infra.yml
> +    command: [--mysql-native-password=ON]
We didn't notice that the command should be changed as mysql version is updated.
Thanks for your fix.

2024-06-27 12:06 UTC, IMHOJEONG commented on docker/docker-compose.infra.yml
> +    platform: linux/arm64/v8
Oh, that's a good idea.

2024-06-27 12:06 UTC, IMHOJEONG commented on docker/docker-compose.infra.yml
> +      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=AIotplatform9((
Yep, that's a good idea! I will reflect it

2024-06-27 12:11 UTC, IMHOJEONG commented
@h4l-yup hello! I made changes based on the feedback you provided. How do you think?

2024-06-27 13:04 UTC, h4l-yup commented
@IMHOJEONG 

Thanks a lot for your fixes!! 👍 

I think there are some small things to make it better, so I suggest below.

1. docker-compose file for arm64 is now named armd64. I think it is a typo.
2. README.md in the root folder has some links to old docker-compose.infra.yml file, and as you changed the infra docker-compose file name, it seems the links are broken. Would you fix those links as well?
3. You might have not noticed the [contributing guide](https://github.com/line/abc-user-feedback/blob/main/CONTRIBUTING.md), actually we suggest to make a PR toward `dev` branch, not `main` branch as we have internal test process for deployment. Would you change the base branch of PR from `main` to `dev`? I tried to change but it seems there is a conflict so it would be great if you change the base branch. If it difficult to resolve, I can just handle it so just tell me if you have a trouble on it.

2024-06-28 05:24 UTC, IMHOJEONG commented
hello! Thank you so much for your feedback. I referenced it, edited it, and created a new PR. 

This PR will then be closed.

2024-06-28 05:24 UTC, closed without merging